logging:
  level: INFO
  loggers:
    com.github.sebastianfrey.joa: DEBUG
server:
  rootPath: /
views:
  freemarker:
    strict_syntax: true
    template_update_delay: 0
    cache_storage: freemarker.cache.NullCacheStorage
    default_encoding: "UTF-8"
joa:
  gpkg:
    worksapce: /workspaces/joa/data/
    runtime: mod_spatialite