logging:
  level: INFO
  loggers:
    com.github.sebastianfrey.joa: INFO
server:
  rootPath: /
views:
  freemarker:
    strict_syntax: true
    template_exception_handler: "rethrow"
    default_encoding: "UTF-8"
joa:
  gpkg:
    worksapce: /data/joa/workspace/
    runtime: mod_spatialite