name: "pre-release"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3.5.1
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Install dependencies
        run: >
          sudo apt-get update && export DEBIAN_FRONTEND=noninteractive \
            && sudo apt-get -y install --no-install-recommends gdal-bin sqlite3 libsqlite3-mod-spatialite
      - name: "Build & test"
        run: mvn -B package --file pom.xml
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            target/*.jar
